# Generated by Django 6.0.2 on 2026-03-07 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='email',
        ),
        migrations.RemoveField(
            model_name='barber',
            name='name',
        ),
        migrations.AddField(
            model_name='barber',
            name='user',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='barber', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
