# Generated by Django 6.0.2 on 2026-03-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_barber_email_remove_barber_name_barber_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='barbers',
            field=models.ManyToManyField(blank=True, to='core.barber'),
        ),
    ]
