# Generated by Django 6.0.2 on 2026-03-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_service_barbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='barbers',
        ),
        migrations.AddField(
            model_name='barber',
            name='services',
            field=models.ManyToManyField(blank=True, to='core.service'),
        ),
    ]
