# Generated by Django 6.0.2 on 2026-03-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_service_barbers_barber_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Dinheiro'), ('pix', 'Pix'), ('card', 'Cartão')], default='cash', max_length=10),
        ),
    ]
